title: HagenMagpie-Blog
description: "A blog about programming, technology, and life."
author:
  name: "HagenMagpie"
  email: "hagenmagpie@proton.me"
  url: "hagenmagpie.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "HagenMagpie"
year : "2023"
